spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/lucio_bot
    username: postgres
    password: postgres
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}
    language: ${DISCORD_BOT_LANGUAGE:pt-BR}
  admin:
    server:
      id: 1285780760439033897
    user:
      id: 440942191800745984

youtube:
  api:
    refresh-token: ${YOUTUBE_API_REFRESH_TOKEN}
spotify:
  client:
    secret: ${SPOTIFY_CLIENT_SECRET}
    id: ${SPOTIFY_CLIENT_ID}
